# SPDX-License-Identifier: Apache-2.0
# Note (Jiaxin Deng): independent weights keep this CI topology free of the
# CUDA-IPC lifecycle while fixed per-replica budgets bound memory demand.

config_cls: MossTTSLocalPipelineConfig
name: mossl
model_path: OpenMOSS-Team/MOSS-TTS-Local-Transformer-v1.5

stage_overrides:
  tts_engine:
    runtime:
      resources:
        total_gpu_memory_fraction: 0.45
      sglang_server_args:
        mem_fraction_static: 0.30

runtime_overrides:
  tts_engine:
    server_args_overrides:
      max_total_tokens: 30000
